CMD: 'python train.py'

HPARAMS: [
  {
    dataset: xxx,
    cv: 0,
    fp16: true,
    crop_size: "720,1440",
    poly_exp: 2,
    n_scales: "0.5,1.0",
    supervised_mscale_loss_wt: 0.05,
    arch: ocrnet.HRNet_Mscale,
    result_dir: sweep_xxx,
    RUNX.TAG: '{arch}',
    
    bs_trn: [1, 2, 4, 8],
    lr: [5e-1,5e-2,5e-3,5e-4,5e-5],
    solver: ['sgd', 'adam']
  },
]