# CMD: "python -m torch.distributed.launch --nproc_per_node=2 train.py"
CMD: "python train.py"

HPARAMS: [
  {
  #  arch: xxx.wcid,
   arch: test2.testnet,
   dataset: xxx,
  #  dataset: railsem19,
   result_dir: LOGDIR,
   RUNX.TAG: '{dataset}/down3,4-5,5Iup1,2-5,5',
   n_scales: "0.5,1.0",
  #  crop_size: "160,320",
  #  class_uniform_tile: 160,
   crop_size: "304,720",
   class_uniform_tile: 304,
   full_crop_training: True,
  #  lr: 1e-3,
   lr: 5e-4,
  #  rmi_loss: true,
   optimizer: "adam",
   amsgrad: true,
   poly_exp: 2,
   supervised_mscale_loss_wt: 0.05,
   weight_decay: 5e-5,
   max_epoch: 150,
  #  syncbn: true,
  #  apex: true,
   fp16: true,
   gblur: True,
   brt_aug: True,
   bg_swap: True,
  #  snapshot: "/home/s0559816/Desktop/semantic-segmentation/logs/train_test/railsem19/test2.testnet_hysterical-quetzal_2022.02.05_12.30/best_checkpoint_ep146.pth"
  },
]
