# CMD: "python -m torch.distributed.launch --nproc_per_node=2 train.py"
CMD: "python train.py"

HPARAMS: [
  {
  #  arch: wcid.wcid_se,
   arch: wcid.wcid_se_mscale,
   dataset: xxx,
  #  dataset: railsem19,
   result_dir: LOGDIR,
   RUNX.TAG: '{arch}-{dataset}',
   n_scales: "0.5,1.0",
   crop_size: "304,720",
   class_uniform_tile: 304,
   full_crop_training: True,
   lr: 5e-4,
  #  rmi_loss: true,
   optimizer: "adam",
   amsgrad: true,
   poly_exp: 2,
   supervised_mscale_loss_wt: 0.05,
   weight_decay: 5e-5,
   max_epoch: 150,
  #  syncbn: true,
  #  apex: true,
   fp16: true,
   gblur: True,
   brt_aug: True,
   bg_swap: True,
  #  snapshot: /home/s0559816/Desktop/semantic-segmentation/logs/train_wcid_se/wcid.wcid_se_mscale-railsem19_majestic-zebra_2022.01.23_12.17/best_checkpoint_ep119.pth,
  },
]
