CMD: "python train.py"
# CMD: "python -m torch.distributed.launch --nproc_per_node=2 train.py"

HPARAMS: [
  {
   arch: ocrnet.HRNet_Mscale,
   result_dir: LOGDIR,
   dataset: se_perception,
  #  dataset: railsem19,
   n_scales: "0.5,1.0",
   lr: 5e-4,
   bs_trn: 2,
   poly_exp: 2,
   supervised_mscale_loss_wt: 0.05,
   class_uniform_pct: 0.5,
   weight_decay: 5e-5,
   max_epoch: 150,
   
   crop_size: "540,960",
   class_uniform_tile: 120,
  
   scale_min: 0.8,
   scale_max: 1.0,
   crop_probability: 0, 

   hflip: 0.5,
   randomBrightnessContrast: 0.2,
   rotate_min: -2.5, 
   rotate_max: 2.5,
   rotate_probability:  0.9, 

   motionBlur: 0.1,
   bg_swap: True,

  #  rmi_loss: true,

  # rmi_loss does not work with fp16
   fp16: true,
   optimizer: "adam",
   amsgrad: true,

  # does not work without apex's C++ extensions
  #  apex: true,
  #  syncbn: true,

   RUNX.TAG: '{arch}/{crop_size}/{class_uniform_tile}/',
  },
]
