CMD: "python train.py"

HPARAMS: [
  {
   arch: ocrnet.HRNet_Mscale,
   result_dir: LOGDIR,
   RUNX.TAG: '{arch}',
   dataset: xxx,
   crop_size: "304,720",
   bs_trn: 1,
   poly_exp: 2,
   lr: 5e-4,
   n_scales: "0.5,1.0,2.0",
   optimizer: "adam",
   class_uniform_tile: 304,
   supervised_mscale_loss_wt: 0.05,
   fp16: true,
   gblur: True,
   brt_aug: True,
   bg_swap: True,
   full_crop_training: True,
   class_uniform_pct: 1,
  },
]
