# CMD: "python -m torch.distributed.launch --nproc_per_node=2 train.py"
CMD: "python train.py"

HPARAMS: [
  {
   arch: test2.testnet_mscale,
  #  arch: test2.testnet,
   dataset: xxx,
   result_dir: LOGDIR,
   n_scales: "0.5,1.0",
   crop_size: "400,800",
   class_uniform_tile: 100,
   full_crop_training: True,
   lr: 5e-4,
   optimizer: "adam",
   amsgrad: true,
   poly_exp: 2,
   supervised_mscale_loss_wt: 0.05,
   weight_decay: 5e-5,
   max_epoch: 150,
  #  syncbn: true,
  #  apex: true,
   fp16: true,
   gblur: True,
   brt_aug: True,
   bg_swap: True,
  #  snapshot: ["/home/s0559816/Desktop/semantic-segmentation/logs/train_test/railsem192/test2.testnet/down4_[5,5]__up1_[5,5]/_amazing-swan_2022.02.08_17.26/best_checkpoint_ep113.pth"]
  },
]
