# CMD: "python -m torch.distributed.launch --nproc_per_node=2 train.py"
CMD: "python train.py"

HPARAMS: [
  {
  #  arch: xxx.wcid,
   arch: test2.testnet_mscale,
   dataset: xxx,
   result_dir: LOGDIR,
   RUNX.TAG: '{arch}',
   n_scales: "0.5,1.0",
  #  crop_size: "160,320",
  #  class_uniform_tile: 160,
   crop_size: "304,720",
   class_uniform_tile: 304,
   full_crop_training: True,
   lr: 5e-4,
  #  rmi_loss: true,
   optimizer: "adam",
   amsgrad: true,
   poly_exp: 2,
   supervised_mscale_loss_wt: 0.05,
   weight_decay: 5e-5,
   max_epoch: 150,
  #  syncbn: true,
  #  apex: true,
   fp16: true,
   gblur: True,
   brt_aug: True,
   bg_swap: True,
  },
]
